[build]
  command = "npm run build:ssr && npm run prerender"
  publish = "dist/portfolio-web/browser"

[functions]
  node_bundler = "esbuild"

[context.production.environment]
  NETLIFY_USE_NETLIFY_ANGULAR_RUNTIME = "false"
